# Site settings
title: The Pensieve
email: piyushahuja.in@gmail.com
description: "My thoughts on philosophy, maths, programming, rowing."
baseurl: ""
url: "http://piyushahuja.com"
author: Piyush Ahuja


# Build settings
markdown: kramdown
permalink: pretty


