# Site settings
title: The Pensieve
email: piyushahuja.in@gmail.com
description: "This is my website"
baseurl: ""
url: "http://piyushahuja.com"
author: 


# Build settings
markdown: kramdown
permalink: pretty


