# Site settings
title: Piyush Ahuja
email: piyushahuja.in@gmail.com
description: "This is Piyush Ahuja's website"
baseurl: ""
url: "http://piyushahuja.com"
author: "Piyush Ahuja"


# Build settings
markdown: kramdown
permalink: pretty


