# Site settings
title: Piyush's Notes
email: piyushahuja.in@gmail.com
description: "Some passably good ideas"
baseurl: ""
url: "http://piyushahuja.com"
author: Piyush Ahuja


# Build settings
markdown: kramdown
permalink: pretty


